class RiskConfig:

    PAPER_BALANCE = 10000
    RISK_PERCENT = 1.0
    MAX_POSITION_PERCENT = 10.0

    TAKE_PROFIT_PERCENT = 1.0
    STOP_LOSS_PERCENT = 0.5

    AUTO_INTERVAL_SECONDS = 60
    SCAN_LIMIT = 5